#!/bin/bash
base=${0%/*}
if [ "x$2" == "x" ]; then
        echo "Usage: $0 <DmgFile> <MountDir>"
        exit 1
fi
dmgFile=$1
mountDir=$2
if [ -e "${mountDir}/notmounted" ]; then
	echo Not mounted...
else
	echo Trying to umount...
	umount ${mountDir}
	exit $?
fi
